owner: derogab # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: derogab.com
    url: https://derogab.com
  - name: derosagabriele.com
    url: https://derosagabriele.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.derogab.com
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/4183824?v=4
  name: Status
  introTitle: "**Status Dashboard** / uptime monitor" 
  introMessage: " "
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
